{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "response = requests.get(\"https://www.motherjones.com/\")\n",
    "doc = BeautifulSoup(response.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The USDA Wants to Make Farms Climate-Friendly. Will It Work?\n",
      "Here’s What Climate Scientists Are Really Saying About This Catastrophic Summer\n",
      "The Pandemic Is Roaring Back Where Vaccination Rates Are Low\n",
      "Biden Vows to Appeal Judge’s Ruling Suspending DACA\n",
      "Matt Gaetz and Marjorie Taylor Greene Can’t Find Anyone Willing to Host Their California Rally\n",
      "For Minimum Wage Workers, Rent Is Now Unaffordable in Every County in America\n",
      "Facebook Official Bites Back at Biden, Insisting That the Platform “Saves Lives”\n",
      "How to Beat an Invisible Enemy: Indoor Air Pollution\n",
      "Two Men Were Just Charged With Planning to Bomb a Democratic Party Building to Avenge Trump\n",
      "One Culprit in the Horrific Death Toll From Europe’s Flooding: Climate Change\n",
      "“When There’s a Disaster, That’s When People Want to Know About Haiti”\n",
      "Five Ways a Dark Money Group Is Trying to Rig Our Elections\n",
      "Leaked Video: Dark Money Group Brags About Writing GOP Voter Suppression Bills Across the Country\n",
      "In 2015, Caitlyn Jenner Wanted Trans Athletes to Play as “Who They Really Are.” What Changed?\n",
      "I Can’t Stop Staring at This Siberian Mosquito Tornado\n",
      "Chicago Banker Convicted of Paying Paul Manafort Bribes to Influence Trump\n",
      "Texas Dems to Biden, Congress: Show the Same Courage We’ve Shown to Protect Voting Rights\n",
      "The National Spelling Bee Finals, Canceled by COVID Last Year, Are Tonight. Take Our Very Serious Quiz.\n",
      "“A Vegetable Oasis in an Urban Landscape”\n",
      "60 Years After the Yankees Told Her the Dugout Was No Place for a Girl, She Threw Out the First Pitch\n",
      "The Moral Panic Over Critical Race Theory Is Coming for a North Carolina Teacher of the Year\n",
      "Canada Is Beating the United States at Vaccination\n",
      "Illinois Becomes the First State to Block Cops From Lying to Kids\n",
      "Corporate Giants Have Been Lobbying Against Their Own Emissions Targets\n",
      "We Can Finally See How Tahiti’s Tiny Tree Snails Evade Fierce Predators\n",
      "The Pandemic Made Science More Accessible Than Ever. Let’s Keep It That Way.\n",
      "Telehealth Should Be Here to Stay\n",
      "Cory Booker Just Picked a Fight With Giant Meatpackers\n",
      "Why the Northwest’s “Heat Dome” Is So Dangerous\n",
      "Darnella Frazier Filmed George Floyd’s Murder. The Minneapolis Police Just Killed Her Uncle.\n",
      "The Pandemic Proved We Don’t Need Bail\n",
      "How Merrick Garland Acts Like Donald Trump’s Lawyer\n",
      "Juneteenth at the Border: Families Reunite With Hugs and Benedictions. Then Their Three Minutes Are Up.\n",
      "Is Trans Telehealth the Future—or Just a Cash Grab?\n",
      "Old People in Prison Were Left to Die From COVID. It Didn’t Have to Be That Way.\n",
      "The Escape From the Billionaire Meme Mogul\n",
      "Schools Spent Millions on High-Tech Air Purifiers. But Are They Actually Making Things Worse?\n",
      "We Need to Understand How We Got to January 6 Before We Can Move Forward\n",
      "A Radical Idea for Forcing Vaccine Companies to Share Knowledge With the World\n",
      "Doctor, Lawyer, Insurrectionist: The Radicalization of Simone Gold\n",
      "“A Jewel for Our Community”: How LA Residents Are Reclaiming Industrial Spaces\n"
     ]
    }
   ],
   "source": [
    "# Get everything with the class of hed\n",
    "# and then loop through them each and print out the text\n",
    "titles = doc.select('.hed')\n",
    "for title in titles:\n",
    "    print(title.text.strip())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 278,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "41"
      ]
     },
     "execution_count": 278,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(titles)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'title': 'Two Men Were Just Charged With Planning to Bomb a Democratic Party Building to Avenge Trump', 'byline': 'Hannah Levintova'}\n"
     ]
    }
   ],
   "source": [
    "#row['byline'] = story.select_one('.byline').text.strip()\n",
    "#print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 280,
   "metadata": {},
   "outputs": [],
   "source": [
    "#look for lead story\n",
    "#doc.select('.layout-3')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 252,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----\n",
      "{'title': 'The USDA Wants to Make Farms Climate-Friendly. Will It Work?', 'byline': 'Leah Douglas', 'URL': 'https://www.motherjones.com/environment/2021/07/farmers-climate-change-conservation-reserve-program/'}\n"
     ]
    }
   ],
   "source": [
    "# each one of these is going to be a row\n",
    "\n",
    "stories = doc.select('.layout-3')\n",
    "# Starting off without ANY rows\n",
    "rows = []\n",
    "\n",
    "for story in stories:\n",
    "    print(\"----\")\n",
    "    row = {}\n",
    "    row['title'] = story.select_one('.hed').text.strip()\n",
    "    row['byline'] = story.select_one('.byline').text.strip()\n",
    "    try:\n",
    "        row['URL'] = story.find('a')['href']\n",
    "    except:\n",
    "        print(\"Couldn't find a link.\")\n",
    "    print(row)\n",
    "    rows.append(row)\n",
    "\n",
    "    # When we're done adding info to our row, we're going to add it into our list\n",
    "    # of rows\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 253,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>byline</th>\n",
       "      <th>URL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The USDA Wants to Make Farms Climate-Friendly....</td>\n",
       "      <td>Leah Douglas</td>\n",
       "      <td>https://www.motherjones.com/environment/2021/0...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               title        byline  \\\n",
       "0  The USDA Wants to Make Farms Climate-Friendly....  Leah Douglas   \n",
       "\n",
       "                                                 URL  \n",
       "0  https://www.motherjones.com/environment/2021/0...  "
      ]
     },
     "execution_count": 253,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#make first dataframe\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame(rows)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 281,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----\n",
      "{'title': 'Here’s What Climate Scientists Are Really Saying About This Catastrophic Summer', 'byline': 'Sofia Andrade', 'url': 'https://www.motherjones.com/environment/2021/07/heres-what-climate-scientists-are-really-saying-about-this-catastrophic-summer/'}\n",
      "----\n",
      "{'title': 'The Pandemic Is Roaring Back Where Vaccination Rates Are Low', 'byline': 'Noah Lanard', 'url': 'https://www.motherjones.com/politics/2021/07/coronavirus-pandemic-arkansas-delta/'}\n",
      "----\n",
      "{'title': 'Biden Vows to Appeal Judge’s Ruling Suspending DACA', 'byline': 'Jamilah King', 'url': 'https://www.motherjones.com/politics/2021/07/biden-vows-to-appeal-judges-ruling-suspending-daca/'}\n",
      "----\n",
      "{'title': 'Matt Gaetz and Marjorie Taylor Greene Can’t Find Anyone Willing to Host Their California Rally', 'byline': 'Aaron Wiener', 'url': 'https://www.motherjones.com/politics/2021/07/matt-gaetz-and-marjorie-taylor-greene-cant-find-anyone-willing-to-host-their-california-rally/'}\n",
      "----\n",
      "{'title': 'For Minimum Wage Workers, Rent Is Now Unaffordable in Every County in America', 'byline': 'Hannah Levintova', 'url': 'https://www.motherjones.com/politics/2021/07/for-minimum-wage-workers-rent-is-now-unaffordable-in-every-county-in-america/'}\n",
      "----\n",
      "{'title': 'Facebook Official Bites Back at Biden, Insisting That the Platform “Saves Lives”', 'byline': 'Jamilah King', 'url': 'https://www.motherjones.com/politics/2021/07/facebook-official-bites-back-at-biden-insisting-that-the-platform-saves-lives/'}\n",
      "----\n",
      "{'title': 'Two Men Were Just Charged With Planning to Bomb a Democratic Party Building to Avenge Trump', 'byline': 'Hannah Levintova', 'url': 'https://www.motherjones.com/politics/2021/07/two-men-were-just-charged-with-planning-to-bomb-a-democratic-party-building-to-avenge-trump/'}\n",
      "----\n",
      "{'title': 'One Culprit in the Horrific Death Toll From Europe’s Flooding: Climate Change', 'byline': 'Hannah Levintova', 'url': 'https://www.motherjones.com/environment/2021/07/one-culprit-in-the-horrific-death-toll-from-europes-flooding-climate-change/'}\n",
      "----\n",
      "{'title': '“When There’s a Disaster, That’s When People Want to Know About Haiti”', 'byline': 'Nathalie Baptiste', 'url': 'https://www.motherjones.com/politics/2021/07/when-theres-a-disaster-thats-when-people-want-to-know-about-haiti-a-dispatch-from-the-diaspora/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/05/5-ways-a-dark-money-group-is-trying-to-rig-our-elections/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/05/heritage-foundation-dark-money-voter-suppression-laws/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/05/caitlyn-jenner-espys-trans-sports/'}\n",
      "----\n",
      "{'title': 'I Can’t Stop Staring at This Siberian Mosquito Tornado', 'byline': 'Clint Hendler', 'url': 'https://www.motherjones.com/mojo-wire/2021/07/siberian-mosquito-tornado/'}\n",
      "----\n",
      "{'title': 'Chicago Banker Convicted of Paying Paul Manafort Bribes to Influence Trump', 'byline': 'Russ Choma', 'url': 'https://www.motherjones.com/mojo-wire/2021/07/paul-manafort-stephen-calk-bribes-donald-trump/'}\n",
      "----\n",
      "{'title': 'Texas Dems to Biden, Congress: Show the Same Courage We’ve Shown to Protect Voting Rights', 'byline': 'Inae Oh', 'url': 'https://www.motherjones.com/mojo-wire/2021/07/texas-democrats-voting-rights/'}\n",
      "----\n",
      "{'title': 'The National Spelling Bee Finals, Canceled by COVID Last Year, Are Tonight. Take Our Very Serious Quiz.', 'byline': 'Daniel King', 'url': 'https://www.motherjones.com/recharge/2021/07/national-spelling-bee-is-back-after-covid-cancellation/'}\n",
      "----\n",
      "{'title': '“A Vegetable Oasis in an Urban Landscape”', 'byline': 'Jacob Rosenberg', 'url': 'https://www.motherjones.com/recharge/2021/07/a-vegetable-oasis-in-an-urban-landscape/'}\n",
      "----\n",
      "{'title': '60 Years After the Yankees Told Her the Dugout Was No Place for a Girl, She Threw Out the First Pitch', 'byline': 'Amanda Silverman', 'url': 'https://www.motherjones.com/recharge/2021/06/yankees-bat-girl-60-year-dream-go-gwen/'}\n",
      "----\n",
      "{'title': 'Canada Is Beating the United States at Vaccination', 'byline': 'Noah Lanard', 'url': 'https://www.motherjones.com/politics/2021/07/canada-is-beating-the-united-states-at-vaccination/'}\n",
      "----\n",
      "{'title': 'Illinois Becomes the First State to Block Cops From Lying to Kids', 'byline': 'Noah Lanard', 'url': 'https://www.motherjones.com/politics/2021/07/police-interrogation-illinois-minors-children/'}\n",
      "----\n",
      "{'title': 'Corporate Giants Have Been Lobbying Against Their Own Emissions Targets', 'byline': 'Emily Pontecorvo', 'url': 'https://www.motherjones.com/environment/2021/07/corporate-giants-have-been-lobbying-against-their-own-emissions-targets/'}\n",
      "----\n",
      "{'title': 'We Can Finally See How Tahiti’s Tiny Tree Snails Evade Fierce Predators', 'byline': 'Hannah Thomasy', 'url': 'https://www.motherjones.com/environment/2021/07/we-can-finally-see-how-tahitis-tiny-tree-snails-evade-fierce-predators/'}\n",
      "----\n",
      "{'title': 'The Pandemic Made Science More Accessible Than Ever. Let’s Keep It That Way.', 'byline': 'Jackie Flynn Mogensen', 'url': 'https://www.motherjones.com/politics/2021/07/the-pandemic-made-science-more-accessible-than-ever-lets-keep-it-that-way/'}\n",
      "----\n",
      "{'title': 'Telehealth Should Be Here to Stay', 'byline': 'Andrea Guzman', 'url': 'https://www.motherjones.com/politics/2021/07/telehealth-should-be-here-to-stay/'}\n",
      "----\n",
      "{'title': 'Cory Booker Just Picked a Fight With Giant Meatpackers', 'byline': 'Tom Philpott', 'url': 'https://www.motherjones.com/food/2021/07/cory-booker-meat-meatpackers-beef-corporate-consolidation/'}\n",
      "----\n",
      "{'title': 'Why the Northwest’s “Heat Dome” Is So Dangerous', 'byline': 'Julia Lurie', 'url': 'https://www.motherjones.com/environment/2021/06/heat-dome-seattle-portland-northwest-drought-climate-change-hot/'}\n",
      "----\n",
      "{'title': 'Darnella Frazier Filmed George Floyd’s Murder. The Minneapolis Police Just Killed Her Uncle.', 'byline': 'Samantha Michaels', 'url': 'https://www.motherjones.com/crime-justice/2021/07/darnella-frazier-filmed-george-floyds-murder-the-minneapolis-police-just-killed-her-uncle/'}\n",
      "----\n",
      "{'title': 'The Pandemic Proved We Don’t Need Bail', 'byline': 'Madison Pauly', 'url': 'https://www.motherjones.com/crime-justice/2021/07/the-pandemic-proved-we-dont-need-bail/'}\n",
      "----\n",
      "{'title': 'How Merrick Garland Acts Like Donald Trump’s Lawyer', 'byline': 'Dan Friedman', 'url': 'https://www.motherjones.com/politics/2021/06/merrick-garland-joe-biden-donald-trump-policies-doj-court-cases/'}\n",
      "----\n",
      "{'title': 'Juneteenth at the Border: Families Reunite With Hugs and Benedictions. Then Their Three Minutes Are Up.', 'byline': 'Andrea Guzman', 'url': 'https://www.motherjones.com/politics/2021/06/hugs-not-walls-event-el-paso-juarez-juneteenth/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/07/is-trans-telehealth-the-future-or-just-a-cash-grab/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/06/old-people-in-prison-were-left-to-die-from-covid-it-didnt-have-to-be-that-way/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/crime-justice/2021/06/russian-sergey-grishin-421-media-billionaire-instagram-content-farm-trump-threats/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://www.motherjones.com/politics/2021/05/air-purifier-covid-asthma-unproven-science-coronavirus-ionization/'}\n",
      "----\n",
      "{'title': 'We Need to Understand How We Got to January 6 Before We Can Move Forward', 'byline': 'Fernanda Echavarri', 'url': 'https://www.motherjones.com/politics/2021/06/podcast-january-6-qanon-history-whats-next/'}\n",
      "----\n",
      "{'title': 'A Radical Idea for Forcing Vaccine Companies to Share Knowledge With the World', 'byline': 'Molly Schwartz and Jamilah King', 'url': 'https://www.motherjones.com/politics/2021/05/vaccine-patents-biden-covid-india-dean-baker-pandemic/'}\n",
      "----\n",
      "{'title': 'Doctor, Lawyer, Insurrectionist: The Radicalization of Simone Gold', 'byline': 'Stephanie Mencimer', 'url': 'https://www.motherjones.com/politics/2021/05/doctor-lawyer-insurrectionist-the-radicalization-of-simone-gold/'}\n",
      "----\n",
      "Couldn't find a title.\n",
      "Couldn't find a byline.\n",
      "{'url': 'https://podcasts.apple.com/us/podcast/the-mother-jones-podcast/id1386408605'}\n"
     ]
    }
   ],
   "source": [
    "#find other top stories under separate web structure\n",
    "\n",
    "stories2 = doc.select('.order-1')\n",
    "# Starting off without ANY rows\n",
    "\n",
    "rows2 = []\n",
    "for story2 in stories2:\n",
    "    print(\"----\")\n",
    "    row = {}\n",
    "    \n",
    "    #print(story2)\n",
    " \n",
    "    try:\n",
    "        row['title'] = story2.select_one('.hed').text.strip()\n",
    "    except:\n",
    "        print(\"Couldn't find a title.\")\n",
    "    try:\n",
    "        row['byline']=story2.select_one('.byline').text.strip()\n",
    "    except:\n",
    "        print(\"Couldn't find a byline.\")\n",
    "    try:\n",
    "        row['url'] = story2.find('a')['href']\n",
    "    except:\n",
    "        print(\"Couldn't find a link.\")\n",
    "    print(row)\n",
    "    rows.append(row)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 269,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>byline</th>\n",
       "      <th>url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Here’s What Climate Scientists Are Really Sayi...</td>\n",
       "      <td>Sofia Andrade</td>\n",
       "      <td>https://www.motherjones.com/environment/2021/0...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>The Pandemic Is Roaring Back Where Vaccination...</td>\n",
       "      <td>Noah Lanard</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/c...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Biden Vows to Appeal Judge’s Ruling Suspending...</td>\n",
       "      <td>Jamilah King</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Matt Gaetz and Marjorie Taylor Greene Can’t Fi...</td>\n",
       "      <td>Aaron Wiener</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/m...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>For Minimum Wage Workers, Rent Is Now Unafford...</td>\n",
       "      <td>Hannah Levintova</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/f...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>109</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/a...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>110</th>\n",
       "      <td>We Need to Understand How We Got to January 6 ...</td>\n",
       "      <td>Fernanda Echavarri</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/06/p...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>111</th>\n",
       "      <td>A Radical Idea for Forcing Vaccine Companies t...</td>\n",
       "      <td>Molly Schwartz and Jamilah King</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/v...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>Doctor, Lawyer, Insurrectionist: The Radicaliz...</td>\n",
       "      <td>Stephanie Mencimer</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/d...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://podcasts.apple.com/us/podcast/the-moth...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>114 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                 title  \\\n",
       "0    Here’s What Climate Scientists Are Really Sayi...   \n",
       "1    The Pandemic Is Roaring Back Where Vaccination...   \n",
       "2    Biden Vows to Appeal Judge’s Ruling Suspending...   \n",
       "3    Matt Gaetz and Marjorie Taylor Greene Can’t Fi...   \n",
       "4    For Minimum Wage Workers, Rent Is Now Unafford...   \n",
       "..                                                 ...   \n",
       "109                                                NaN   \n",
       "110  We Need to Understand How We Got to January 6 ...   \n",
       "111  A Radical Idea for Forcing Vaccine Companies t...   \n",
       "112  Doctor, Lawyer, Insurrectionist: The Radicaliz...   \n",
       "113                                                NaN   \n",
       "\n",
       "                              byline  \\\n",
       "0                      Sofia Andrade   \n",
       "1                        Noah Lanard   \n",
       "2                       Jamilah King   \n",
       "3                       Aaron Wiener   \n",
       "4                   Hannah Levintova   \n",
       "..                               ...   \n",
       "109                              NaN   \n",
       "110               Fernanda Echavarri   \n",
       "111  Molly Schwartz and Jamilah King   \n",
       "112               Stephanie Mencimer   \n",
       "113                              NaN   \n",
       "\n",
       "                                                   url  \n",
       "0    https://www.motherjones.com/environment/2021/0...  \n",
       "1    https://www.motherjones.com/politics/2021/07/c...  \n",
       "2    https://www.motherjones.com/politics/2021/07/b...  \n",
       "3    https://www.motherjones.com/politics/2021/07/m...  \n",
       "4    https://www.motherjones.com/politics/2021/07/f...  \n",
       "..                                                 ...  \n",
       "109  https://www.motherjones.com/politics/2021/05/a...  \n",
       "110  https://www.motherjones.com/politics/2021/06/p...  \n",
       "111  https://www.motherjones.com/politics/2021/05/v...  \n",
       "112  https://www.motherjones.com/politics/2021/05/d...  \n",
       "113  https://podcasts.apple.com/us/podcast/the-moth...  \n",
       "\n",
       "[114 rows x 3 columns]"
      ]
     },
     "execution_count": 269,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#build second data frame of other top stories\n",
    "df2 = pd.DataFrame(rows)\n",
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 276,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>byline</th>\n",
       "      <th>URL</th>\n",
       "      <th>url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The USDA Wants to Make Farms Climate-Friendly....</td>\n",
       "      <td>Leah Douglas</td>\n",
       "      <td>https://www.motherjones.com/environment/2021/0...</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Here’s What Climate Scientists Are Really Sayi...</td>\n",
       "      <td>Sofia Andrade</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/environment/2021/0...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>The Pandemic Is Roaring Back Where Vaccination...</td>\n",
       "      <td>Noah Lanard</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/c...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Biden Vows to Appeal Judge’s Ruling Suspending...</td>\n",
       "      <td>Jamilah King</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Matt Gaetz and Marjorie Taylor Greene Can’t Fi...</td>\n",
       "      <td>Aaron Wiener</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/07/m...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>109</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/a...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>110</th>\n",
       "      <td>We Need to Understand How We Got to January 6 ...</td>\n",
       "      <td>Fernanda Echavarri</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/06/p...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>111</th>\n",
       "      <td>A Radical Idea for Forcing Vaccine Companies t...</td>\n",
       "      <td>Molly Schwartz and Jamilah King</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/v...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>Doctor, Lawyer, Insurrectionist: The Radicaliz...</td>\n",
       "      <td>Stephanie Mencimer</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://www.motherjones.com/politics/2021/05/d...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://podcasts.apple.com/us/podcast/the-moth...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>115 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                 title  \\\n",
       "0    The USDA Wants to Make Farms Climate-Friendly....   \n",
       "0    Here’s What Climate Scientists Are Really Sayi...   \n",
       "1    The Pandemic Is Roaring Back Where Vaccination...   \n",
       "2    Biden Vows to Appeal Judge’s Ruling Suspending...   \n",
       "3    Matt Gaetz and Marjorie Taylor Greene Can’t Fi...   \n",
       "..                                                 ...   \n",
       "109                                                NaN   \n",
       "110  We Need to Understand How We Got to January 6 ...   \n",
       "111  A Radical Idea for Forcing Vaccine Companies t...   \n",
       "112  Doctor, Lawyer, Insurrectionist: The Radicaliz...   \n",
       "113                                                NaN   \n",
       "\n",
       "                              byline  \\\n",
       "0                       Leah Douglas   \n",
       "0                      Sofia Andrade   \n",
       "1                        Noah Lanard   \n",
       "2                       Jamilah King   \n",
       "3                       Aaron Wiener   \n",
       "..                               ...   \n",
       "109                              NaN   \n",
       "110               Fernanda Echavarri   \n",
       "111  Molly Schwartz and Jamilah King   \n",
       "112               Stephanie Mencimer   \n",
       "113                              NaN   \n",
       "\n",
       "                                                   URL  \\\n",
       "0    https://www.motherjones.com/environment/2021/0...   \n",
       "0                                                  NaN   \n",
       "1                                                  NaN   \n",
       "2                                                  NaN   \n",
       "3                                                  NaN   \n",
       "..                                                 ...   \n",
       "109                                                NaN   \n",
       "110                                                NaN   \n",
       "111                                                NaN   \n",
       "112                                                NaN   \n",
       "113                                                NaN   \n",
       "\n",
       "                                                   url  \n",
       "0                                                  NaN  \n",
       "0    https://www.motherjones.com/environment/2021/0...  \n",
       "1    https://www.motherjones.com/politics/2021/07/c...  \n",
       "2    https://www.motherjones.com/politics/2021/07/b...  \n",
       "3    https://www.motherjones.com/politics/2021/07/m...  \n",
       "..                                                 ...  \n",
       "109  https://www.motherjones.com/politics/2021/05/a...  \n",
       "110  https://www.motherjones.com/politics/2021/06/p...  \n",
       "111  https://www.motherjones.com/politics/2021/05/v...  \n",
       "112  https://www.motherjones.com/politics/2021/05/d...  \n",
       "113  https://podcasts.apple.com/us/podcast/the-moth...  \n",
       "\n",
       "[115 rows x 4 columns]"
      ]
     },
     "execution_count": 276,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#combine the two dataframes and check\n",
    "\n",
    "frames = [df, df2]\n",
    "\n",
    "#print(frames)\n",
    "mojoresult = pd.concat(frames)\n",
    "mojoresult\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 277,
   "metadata": {},
   "outputs": [],
   "source": [
    "#download as csv\n",
    "mojoresult.to_csv(\"mojo-headlines.csv\", index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
